

select * from customeranalysis
select top 10 * from customeranalysis

--What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue from customeranalysis
group by gender
order by gender

--Which customer used a discount bill but still spent more than the average purchase?
with cte as (
select * from customeranalysis where discount_applied = 'Yes'
)
select customer_id, sum(purchase_amount) as revenue from cte 
group by customer_id
having sum(purchase_amount) > (select avg(purchase_amount) as avg_revenue from customeranalysis)

--which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as avg_review from customeranalysis
group by item_purchased
order by avg(review_rating) desc

--Compare the average purchase amounts between standard and express shipping
select shipping_type , avg(purchase_amount) as revenue from customeranalysis where shipping_type in ('Standard','Express')
group by shipping_type
order by avg(purchase_amount) desc

--Do subscribed customers spend more? compare average spend and total revenue between subscribers and non_subscribers
select subscription_status,count(customer_id) as total_customers,
sum(purchase_amount) as total_spend,
avg(purchase_amount) as avg_spend from customeranalysis 
group by subscription_status
order by total_spend, avg_spend desc

--which 5 prodcuts have the highest percentage of purchases with discount applied
select top 5 item_purchased,(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)) as discount_rate from customeranalysis
group by item_purchased
order by discount_rate desc

--Select customers into New, Returning and Loyal based on their total number of previous purchases and show count of each segment
with cte as (
select customer_id,previous_purchases,
case when previous_purchases > 10 then 'Loyal'
	when previous_purchases> 3 then 'Returning'
	else 'New'
end as customer_type 
from customeranalysis)
select customer_type, count(*) as total_purchases from cte 
group by customer_type
order by count(*) desc

--What are the top 3 most purchased products within each category
with cte as(
select category, item_purchased, count(customer_id) as  total_orders,
row_number()over(partition by category order by count(customer_id) desc) as rn from customeranalysis
group by category, item_purchased)
select category, item_purchased,rn,total_orders from cte where rn<=3

--Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe
select subscription_status, count(customer_id) from customeranalysis
where previous_purchases>5
group by subscription_status

--what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue from customeranalysis
group by age_group
order by total_revenue desc